name: 搭建环境并编译

on: [push]

jobs:
  build:
    runs-on: windows-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@master
    - uses: conda-incubator/setup-miniconda@v3
      with:
        auto-update-conda：true
        python-version：'3.11.9'
        environment-file: environment.yml
    - name: Archive Release
      uses: thedoctor0/zip-release@0.7.5
      with:
        type: 'zip'
        path: 'server\'
        filename: 'edusync-server.zip'
        exclusions: '*.git* /*node_modules/* .editorconfig'
    - uses: Nuitka/Nuitka-Action@main
      name: Build Client
      with:
        nuitka-version: main
        script-name: client/main.py
        output-file: edusync-client.exe
        onefile: true
    - uses: Nuitka/Nuitka-Action@main
      name: Build Manager
      with:
        nuitka-version: main
        script-name: manager/main.py
        output-file: edusync-manager.exe
        onefile: true
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: upload-build
        path: |
          build\edusync-client.exe
          build\edusync-manager.exe
          build\edusync-server.zip